version: '2.1'

services:

  app:
    restart: unless-stopped
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    volumes: ['app-data:/home/applicatoin']
    ports: ['8080:8080']
    networks:
      public-net:
        aliases:
        - a
        - app
        - appplication

volumes:
  app-data: {}

networks:
  public-net:
